### ISSUE TITLE
Calling create token throws class not found

### ISSUE THREAD

**Issue by TomBeckett** [GetStream/stream-chat-java#16]
Calling the static `io.getstream.chat.java.models.User.createToken`  method outside of the SDK throws a `ClassNotFound` error. For example:

```
java.lang.ClassNotFoundException: io.jsonwebtoken.SignatureAlgorithm
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[na:na]
	at io.getstream.chat.java.models.User.createToken(User.java:1332) ~[stream-chat-java-1.2.0.jar:na]
	at app.squaddy.api.service.external.GetStreamService.createTokenForUser(GetStreamService.java:218) ~[classes/:na]
```

Example usage:

`createToken(chatId, null, null);`

**Comment by akul1994** [comment]
Facing the same issue

**Comment by ferhatelmas** [comment]
Thanks for the report and confirmation! Will address it today!

**Comment by rdonahue77** [comment]
This is not resolved, a related issue is here: https://github.com/GetStream/stream-chat-java/issues/38

**Comment by coderman2022** [comment]
Why are you recommending to add the `io.jsonwebtoken` jjwt dependency when actually `stream-java` depends on the `com.auth0` jwt implementation? In such a case the solution would be to **remove** `io.jsonwebtoken`, not to add it. You can see this dependency here https://mvnrepository.com/artifact/io.getstream.client/stream-java/3.2.4

**Comment by ferhatelmas** [comment]
`stream-java` isn't this SDK/repo, It's this one, https://github.com/getstream/stream-java for feed client.
